/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofifo;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author jose5
 */
public class Grafica extends javax.swing.JFrame {

    /**
     * Creates new form Simulacion
     */
    public Grafica() {
        initComponents();
        setTitle("Simulacion Calendarizacion");
        PanelSimulacion.setLayout(new GridLayout(0, 3));
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        PanelSimulacion = new javax.swing.JPanel();
        addProceso = new javax.swing.JLabel();
        numProceso = new javax.swing.JTextField();
        Numero = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        nomProceso = new javax.swing.JTextField();
        Rafaga = new javax.swing.JLabel();
        rafaProceso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        IniciarSimulacion = new javax.swing.JButton();
        spinnerQuantum = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        agregarProceso = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Simulador de Procesos");
        Titulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Titulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 570, 60));

        PanelSimulacion.setBackground(new java.awt.Color(255, 255, 255));
        PanelSimulacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout PanelSimulacionLayout = new javax.swing.GroupLayout(PanelSimulacion);
        PanelSimulacion.setLayout(PanelSimulacionLayout);
        PanelSimulacionLayout.setHorizontalGroup(
            PanelSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        PanelSimulacionLayout.setVerticalGroup(
            PanelSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );

        jPanel1.add(PanelSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 1100, 620));

        addProceso.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        addProceso.setForeground(new java.awt.Color(0, 0, 0));
        addProceso.setText("Agregar proceso");
        jPanel1.add(addProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 210, 40));

        numProceso.setBackground(new java.awt.Color(255, 255, 255));
        numProceso.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        numProceso.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(numProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 200, 40));

        Numero.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        Numero.setForeground(new java.awt.Color(0, 0, 0));
        Numero.setText("Num:");
        jPanel1.add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 30));

        Nombre.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Nombre:");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 30));

        nomProceso.setBackground(new java.awt.Color(255, 255, 255));
        nomProceso.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        nomProceso.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(nomProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 200, 40));

        Rafaga.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        Rafaga.setForeground(new java.awt.Color(0, 0, 0));
        Rafaga.setText("Rafaga:");
        jPanel1.add(Rafaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 20));

        rafaProceso.setBackground(new java.awt.Color(255, 255, 255));
        rafaProceso.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        rafaProceso.setForeground(new java.awt.Color(0, 0, 0));
        rafaProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rafaProcesoActionPerformed(evt);
            }
        });
        jPanel1.add(rafaProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 200, 40));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 2));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Num", "Proceso", "Rafaga", "T Llegada"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 330, 110));

        IniciarSimulacion.setBackground(new java.awt.Color(0, 0, 0));
        IniciarSimulacion.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        IniciarSimulacion.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSimulacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-play-30.png"))); // NOI18N
        IniciarSimulacion.setText("Simular");
        IniciarSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSimulacionActionPerformed(evt);
            }
        });
        jPanel1.add(IniciarSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, 170, 50));

        spinnerQuantum.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(spinnerQuantum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 200, 40));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Quantum:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, -1));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tabla de procesos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Metricas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 710, -1, -1));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Total procesos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 740, -1, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tiempo espera total:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 780, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("tiemp0 espera promedio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 820, -1, 20));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 740, 110, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 780, 110, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 820, 110, -1));

        agregarProceso.setBackground(new java.awt.Color(0, 0, 0));
        agregarProceso.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        agregarProceso.setForeground(new java.awt.Color(255, 255, 255));
        agregarProceso.setText("AGregar proceso");
        agregarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProcesoActionPerformed(evt);
            }
        });
        jPanel1.add(agregarProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 180, 30));

        Fondo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Fondo2.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 870));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void rafaProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rafaProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rafaProcesoActionPerformed

    private void agregarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProcesoActionPerformed
        // TODO add your handling code here:
        agregarProceso();
        borrar();
    }//GEN-LAST:event_agregarProcesoActionPerformed

    private void IniciarSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSimulacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarSimulacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

private void agregarProceso() {
    int num = Integer.parseInt(numProceso.getText());
    String nombre = nomProceso.getText();
    int rafaga = Integer.parseInt(rafaProceso.getText());

    JPanel processSquare = new JPanel();
    processSquare.setSize(new Dimension(50, 50));
    processSquare.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    processSquare.setBackground(Color.cyan);
    processSquare.setLayout(new BorderLayout());
    
    JLabel numLabel = new JLabel("P: " + num);
    JLabel nameLabel = new JLabel(nombre);
    JLabel burstLabel = new JLabel("Rafaga: "+rafaga);
    
    processSquare.add(numLabel, BorderLayout.NORTH);
    processSquare.add(nameLabel, BorderLayout.CENTER);
    processSquare.add(burstLabel, BorderLayout.SOUTH);
    

    PanelSimulacion.setBackground(Color.white);
    PanelSimulacion.add(processSquare);

    // Forzar el repintado del panel
    PanelSimulacion.revalidate(); // Revalida la estructura del panel
    PanelSimulacion.repaint();    // Vuelve a pintar el panel en la pantalla
}
private void borrar(){
    numProceso.setText("");
    nomProceso.setText("");
    rafaProceso.setText("");
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton IniciarSimulacion;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Numero;
    private javax.swing.JPanel PanelSimulacion;
    private javax.swing.JLabel Rafaga;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel addProceso;
    private javax.swing.JButton agregarProceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField nomProceso;
    private javax.swing.JTextField numProceso;
    private javax.swing.JTextField rafaProceso;
    private javax.swing.JSpinner spinnerQuantum;
    // End of variables declaration//GEN-END:variables
}
